<a href="https://colab.research.google.com/github/hemalatha36/Application-of-python-programming/blob/master/day_3_excercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EXCERCISES

Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000¶
tip : use List Comprehension
ds = pd.Series([0,2, 4, 6, 8..... 10000])

In [1]:
import pandas as pd
ds = pd.Series([x for x in range(10000) if x%2==0])
print(ds)

0          0
1          2
2          4
3          6
4          8
        ... 
4995    9990
4996    9992
4997    9994
4998    9996
4999    9998
Length: 5000, dtype: int64


Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

In [2]:
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [3]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]

In [4]:
import pandas as pd
ds1 = pd.Series([i for i in range(1000) if i%7==0])
ds2 = pd.Series([j for j in range(1000) if j%11==0])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
for i in range(len(ds2)):
    print(i," ",ds1[i]==ds2[i])
for i in range(len(ds2)):
    print(i," ",ds1[i]>ds2[i])
for i in range(len(ds2)):
    print(i," ",ds1[i]<ds2[i])
for i in range(len(ds2)):
    print(i," ",ds1[i]!=ds2[i])

Series1:
0        0
1        7
2       14
3       21
4       28
      ... 
138    966
139    973
140    980
141    987
142    994
Length: 143, dtype: int64
Series2:
0       0
1      11
2      22
3      33
4      44
     ... 
86    946
87    957
88    968
89    979
90    990
Length: 91, dtype: int64
Compare the elements of the said Series:
Equals:
0   True
1   False
2   False
3   False
4   False
5   False
6   False
7   False
8   False
9   False
10   False
11   False
12   False
13   False
14   False
15   False
16   False
17   False
18   False
19   False
20   False
21   False
22   False
23   False
24   False
25   False
26   False
27   False
28   False
29   False
30   False
31   False
32   False
33   False
34   False
35   False
36   False
37   False
38   False
39   False
40   False
41   False
42   False
43   False
44   False
45   False
46   False
47   False
48   False
49   False
50   False
51   False
52   False
53   False
54   False
55   False
56   False
57   False
58   False
59   False
60

Write a Pandas program to convert a NumPy array to a Pandas series.
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]

In [5]:
import numpy as np
import pandas as pd
np_array = np.array([m for m in range(1000) if m%10==0])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350
 360 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530
 540 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690 700 710
 720 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890
 900 910 920 930 940 950 960 970 980 990]
Converted Pandas series:
0       0
1      10
2      20
3      30
4      40
     ... 
95    950
96    960
97    970
98    980
99    990
Length: 100, dtype: int64


Write a Pandas program to convert a given Series to an array.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [6]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1)
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


Write a Pandas program to sort a given Series.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [7]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1)
a.sort()
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


Write a Pandas program to create a subsets of a given series based on value and condition.
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5

In [8]:
import pandas as pd
s = pd.Series([i for i in range(1000) if i%10==0])
print("Original Data Series:")
print(s)
print("\nSubset 1:")
new_s = s[s%7==0]
print(new_s)
print("\nSubset 2:")
new_s1 = s[s%5==0]
print(new_s1)

Original Data Series:
0       0
1      10
2      20
3      30
4      40
     ... 
95    950
96    960
97    970
98    980
99    990
Length: 100, dtype: int64

Subset 1:
0       0
7      70
14    140
21    210
28    280
35    350
42    420
49    490
56    560
63    630
70    700
77    770
84    840
91    910
98    980
dtype: int64

Subset 2:
0       0
1      10
2      20
3      30
4      40
     ... 
95    950
96    960
97    970
98    980
99    990
Length: 100, dtype: int64


Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [9]:
import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


Write a Pandas program to get the elements of an array values into column-wise.
Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

In [10]:
import pandas as pd
a =[x for x in range(1000) if (x%2!=0)and(x%7!=0)]
b =[y for y in range(1000) if (y%2==0)and(y%5!=0)]
c=[z for z in range(1000) if (z%2!=0)and(z%3!=0)]
s1=pd.Series(a)
s2=pd.Series(b)
s3=pd.Series(c)
df = pd.DataFrame({'X':s1,'Y':s2,'Z':s3})
df

X     Y     Z
0      1   2.0   1.0
1      3   4.0   5.0
2      5   6.0   7.0
3      9   8.0  11.0
4     11  12.0  13.0
..   ...   ...   ...
424  991   NaN   NaN
425  993   NaN   NaN
426  995   NaN   NaN
427  997   NaN   NaN
428  999   NaN   NaN

[429 rows x 3 columns]


Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields

In [11]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
df1 = df[['name','score','attempts']]
df1.head(10)

First three rows of the data frame:


name  score  attempts
a  Anastasia   12.5         1
b       Dima    9.0         3
c  Katherine   16.5         2
d      James    NaN         3
e      Emily    9.0         2
f    Michael   20.0         3
g    Matthew   14.5         1
h      Laura    NaN         1
i      Kevin    8.0         2
j      Jonas   19.0         1

Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable

In [14]:
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x) 
y = np.array(x[1:3])
y

Original Array:
[[0.84254452 0.36817726 0.42823048 0.37072075]
 [0.66859278 0.97367101 0.58880099 0.68868979]
 [0.246926   0.43861329 0.0775845  0.58332033]
 [0.15255792 0.75543789 0.45436888 0.18674542]]


array([[0.66859278, 0.97367101, 0.58880099, 0.68868979],
       [0.246926  , 0.43861329, 0.0775845 , 0.58332033]])

Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [15]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.13423776 0.91351364 0.43581642 0.65114723 0.19075137 0.38426242
  0.99454768 0.40267941 0.93189805 0.94078268]
 [0.07375119 0.34584797 0.71441791 0.50088463 0.45444598 0.19460137
  0.86975244 0.90123894 0.49234764 0.44792417]
 [0.76330349 0.46055503 0.32743159 0.49953131 0.38610288 0.57004321
  0.42663164 0.41121564 0.74611941 0.43935981]
 [0.18998399 0.74919157 0.56485953 0.74471488 0.28923711 0.03910229
  0.82298571 0.29645481 0.82793232 0.0905694 ]
 [0.22611217 0.29501312 0.18804975 0.95549653 0.3772591  0.63540027
  0.02613128 0.55627915 0.45403362 0.92578671]
 [0.62673002 0.5617945  0.02365564 0.86856151 0.33773095 0.97838574
  0.66840784 0.05193175 0.35844881 0.66917467]
 [0.95274441 0.6185036  0.54023135 0.30740964 0.61464542 0.44777141
  0.28872114 0.76493697 0.63277246 0.9865811 ]
 [0.28674056 0.37983076 0.87842308 0.65131479 0.21218141 0.91650782
  0.16319038 0.76045778 0.52654151 0.43617467]
 [0.35977368 0.31314242 0.59267292 0.19734539 0.50854789 0.88434

Write a NumPy program to generate 8 random integers between 100 and 300

In [16]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[138 292 205 231 142 186 110 260]


Write a NumPy program to create a random integer nos of size 20 and sort it.

In [17]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.60016934 0.12540263 0.36466987 0.65725965 0.57642675 0.02237904
 0.91060999 0.86122637 0.2262938  0.57409516 0.80714614 0.42830804
 0.35553025 0.77961865 0.51275041 0.9465532  0.65936712 0.58980235
 0.31500714 0.49423168]
Sorted array:
[0.02237904 0.12540263 0.2262938  0.31500714 0.35553025 0.36466987
 0.42830804 0.49423168 0.51275041 0.57409516 0.57642675 0.58980235
 0.60016934 0.65725965 0.65936712 0.77961865 0.80714614 0.86122637
 0.91060999 0.9465532 ]
